// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyjO7u9b_UK7CgRSR3pq8SyXGCZSTyQ7E',
    appId: '1:76341613205:web:8ce49ca53ccbdd0f4e019c',
    messagingSenderId: '76341613205',
    projectId: 'studyku-cd0db',
    authDomain: 'studyku-cd0db.firebaseapp.com',
    storageBucket: 'studyku-cd0db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClAp2GTHf_HzLY24D9ARGlIRIrej5CYAA',
    appId: '1:76341613205:android:de0fbc3694febb8b4e019c',
    messagingSenderId: '76341613205',
    projectId: 'studyku-cd0db',
    storageBucket: 'studyku-cd0db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Sts94fw2WKkSSxdvKCPhZ5UyqVSX61o',
    appId: '1:76341613205:ios:052771614853402a4e019c',
    messagingSenderId: '76341613205',
    projectId: 'studyku-cd0db',
    storageBucket: 'studyku-cd0db.appspot.com',
    iosClientId: '76341613205-okoaue81384q6b1i3mcvvk6impglcj6u.apps.googleusercontent.com',
    iosBundleId: 'com.studyku.study',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Sts94fw2WKkSSxdvKCPhZ5UyqVSX61o',
    appId: '1:76341613205:ios:052771614853402a4e019c',
    messagingSenderId: '76341613205',
    projectId: 'studyku-cd0db',
    storageBucket: 'studyku-cd0db.appspot.com',
    iosClientId: '76341613205-okoaue81384q6b1i3mcvvk6impglcj6u.apps.googleusercontent.com',
    iosBundleId: 'com.studyku.study',
  );
}
